/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Apr 9, 2010, 1:57:22 PM
 */
package com.hyk.proxy.client.launch.gui;

//import com.hyk.proxy.gae.client.httpserver.HttpServer;
import com.hyk.proxy.client.config.ConfigService;
import com.hyk.proxy.client.framework.status.StatusMonitor;
import com.hyk.proxy.client.launch.LocalProxyServer;
import com.hyk.proxy.client.util.ClientUtils;
import com.hyk.proxy.common.Constants;
import com.hyk.proxy.common.ExtensionsLauncher;
import com.hyk.proxy.common.Version;
import com.hyk.proxy.common.update.ProductReleaseDetail.ReleaseDetail;
import com.hyk.proxy.common.update.UpdateCheck.UpdateCheckFactory;
import com.hyk.rpc.core.RpcException;
import java.awt.Cursor;
import java.awt.Desktop;

import java.io.IOException;
import java.net.URI;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 
 * @author qiying.wang
 */
public class GUILauncher extends javax.swing.JFrame
{

	protected static final Logger	logger	= LoggerFactory.getLogger(GUILauncher.class);

	/** Creates new form NewJFrame */
	public GUILauncher() throws Exception
	{
		UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		LookAndFeelInfo[] allFeels = UIManager.getInstalledLookAndFeels();
		for(LookAndFeelInfo feel : allFeels)
		{
			if(feel.getName().contains("Nimbus"))
			{
				UIManager.setLookAndFeel(feel.getClassName());
				break;
			}
		}

		ExtensionsLauncher.init();
		initComponents();
		// setIconImage(new
		// ImageIcon(getClass().getResource("/image/idle.png")).getImage());
		setIconImage(ImageUtil.GAE.getImage());
		setTitle("hyk-proxy-client V" + Version.value);
		// jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("hyk-proxy-client V"
		// + Version.value));
		statusLable.setText("Idle");
		tray = new SysTray(this);

		if(!ConfigService.getDefaultConfig().getHykProxyServerAuths().isEmpty())
		{
			updateExeucteButton();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		executeButton = new javax.swing.JButton();
		configButton = new javax.swing.JButton();
		exitButton = new javax.swing.JButton();
		statusLable = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		statusTextArea = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		shareAppIdTextField = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		shareAppIdButton = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
		javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
		javax.swing.JLabel versionLabel = new javax.swing.JLabel();
		javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
		javax.swing.JLabel vendorLabel = new javax.swing.JLabel();
		javax.swing.JLabel appVendorLabel = new javax.swing.JLabel();
		appHomepageLabel = new javax.swing.JLabel();
		javax.swing.JLabel homepageLabel = new javax.swing.JLabel();
		helpButton = new javax.swing.JButton();
		upgradeButton = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		setLocationByPlatform(true);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosed(java.awt.event.WindowEvent evt)
			{
				formWindowClosed(evt);
			}
		});

		executeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/player_play.png"))); // NOI18N
		executeButton.setText("Start");
		executeButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				executeButtonActionPerformed(evt);
			}
		});

		configButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/configure.png"))); // NOI18N
		configButton.setText("Config");
		configButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				configButtonActionPerformed(evt);
			}
		});

		exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
		exitButton.setText("Exit");
		exitButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				exitButtonActionPerformed(evt);
			}
		});

		statusLable.setText("jLabel3");

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/twitter.png"))); // NOI18N
		jLabel1.setText("<html><font color=\"Blue\"> <u>@yinqiwen</u></font></html>");
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter()
		{
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				jLabel1MouseClicked(evt);
			}
		});
		jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
		{
			public void mouseMoved(java.awt.event.MouseEvent evt)
			{
				jLabel1MouseMoved(evt);
			}
		});

		statusTextArea.setBackground(new java.awt.Color(204, 204, 204));
		statusTextArea.setColumns(15);
		statusTextArea.setEditable(false);
		statusTextArea.setRows(5);
		statusTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));
		jScrollPane1.setViewportView(statusTextArea);

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Google-AppEngine-128.png"))); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel1Layout.createSequentialGroup().addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205,
						javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139,
						javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
						javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(19, Short.MAX_VALUE)).addComponent(jScrollPane1,
				javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE));

		jTabbedPane1.addTab("Main", ImageUtil.HOME, jPanel1);

		jLabel3.setText("My AppID:");

		shareAppIdButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/publish.png"))); // NOI18N
		shareAppIdButton.setText("Share");
		shareAppIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
		shareAppIdButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				shareAppIdButtonActionPerformed(evt);
			}
		});

		jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
		jTextArea2.setColumns(20);
		jTextArea2.setEditable(false);
		jTextArea2.setRows(5);
		jTextArea2.setText("Some thing you must know before sharing your appid:\n1. The shared appid can be used by anybody as \n   'anonymouse' user.\n2. You can use admin tool to control traffic and \n   blacklist for 'anonymouse'.");
		jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Note:"));
		jScrollPane2.setViewportView(jTextArea2);

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Delete-icon.png"))); // NOI18N
		jButton1.setText("Unshare");
		jButton1.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(
						jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPanel2Layout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(shareAppIdTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(shareAppIdButton,
										javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton1)).addComponent(jScrollPane2,
								javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(
						jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(
								shareAppIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(shareAppIdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 23,
								Short.MAX_VALUE).addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
								javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(
						jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(26, 26, 26)));

		jTabbedPane1.addTab("Share!", ImageUtil.PUBLISH, jPanel2);

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dukejdk.png"))); // NOI18N

		appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD,
				appTitleLabel.getFont().getSize() + 4));
		appTitleLabel.setText("hyk-proxy GUI Client");

		appDescLabel.setText("<html>The GUI client of hyk-proxy");

		versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
		versionLabel.setText("Product Version:");

		appVersionLabel.setText(Version.value);

		vendorLabel.setFont(vendorLabel.getFont().deriveFont(vendorLabel.getFont().getStyle() | java.awt.Font.BOLD));
		vendorLabel.setText("Vendor:");

		appVendorLabel.setText("yinqiwen@gmail.com");

		appHomepageLabel.setText("<html><font color=\"Blue\"> <u>http://hyk-proxy.googlecode.com</u></font></html>");
		appHomepageLabel.addMouseListener(new java.awt.event.MouseAdapter()
		{
			public void mouseClicked(java.awt.event.MouseEvent evt)
			{
				appHomepageLabelMouseClicked(evt);
			}
		});
		appHomepageLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
		{
			public void mouseMoved(java.awt.event.MouseEvent evt)
			{
				appHomepageLabelMouseMoved(evt);
			}
		});

		homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD));
		homepageLabel.setText("Home:");

		helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/help.png"))); // NOI18N
		helpButton.setText("Help");
		helpButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				helpButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(
						jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPanel3Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
										jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
												jPanel3Layout.createSequentialGroup().addComponent(versionLabel).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(appVersionLabel)).addComponent(
												appTitleLabel).addGroup(
												jPanel3Layout.createSequentialGroup().addComponent(vendorLabel).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(appVendorLabel)).addGroup(
												jPanel3Layout.createSequentialGroup().addComponent(homepageLabel).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(appHomepageLabel,
														javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(appDescLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
										helpButton).addGap(46, 46, 46)))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(
						jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(
								jPanel3Layout.createSequentialGroup().addComponent(appTitleLabel).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(appDescLabel,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addGroup(
										jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(versionLabel).addComponent(
												appVersionLabel)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
										jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(vendorLabel).addComponent(
												appVendorLabel)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
										jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(homepageLabel).addComponent(
												appHomepageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(helpButton))).addContainerGap(23,
						Short.MAX_VALUE)));

		jTabbedPane1.addTab("About", ImageUtil.ABOUT, jPanel3);

		upgradeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Update.png"))); // NOI18N
		upgradeButton.setText("Upgrade");
		upgradeButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				upgradeButtonActionPerformed(evt);
			}
		});

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/freelance.png"))); // NOI18N

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/world.png"))); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(statusLable,
										javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE).addGap(6, 6, 6)).addGroup(
								layout.createSequentialGroup().addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355,
										javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
												layout.createSequentialGroup().addGap(15, 15, 15).addComponent(jLabel4).addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel6)).addComponent(
												executeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE).addComponent(configButton,
												javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE).addComponent(upgradeButton,
												javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE).addComponent(exitButton,
												javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)).addContainerGap()))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								layout.createSequentialGroup().addGap(19, 19, 19).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel4).addComponent(
												jLabel6)).addGap(18, 18, 18).addComponent(executeButton).addGap(18, 18, 18).addComponent(configButton).addGap(
										18, 18, 18).addComponent(upgradeButton).addGap(18, 18, 18).addComponent(exitButton)).addGroup(
								layout.createSequentialGroup().addContainerGap().addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
										238, javax.swing.GroupLayout.PREFERRED_SIZE))).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(
								statusLable)).addContainerGap()));

		jLabel1.getAccessibleContext().setAccessibleName(
				"<html>This is html text that includes a <font color=\"Blue\"> <u>hyperlink</u></font></html>");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void exit()
	{
		try
		{
			if(null != server)
			{
				getHttpServer().stop();
			}
		}
		catch(Exception ex)
		{
			logger.error("Failed to stop local http server!", ex);
		}
		finally
		{
			System.exit(1);
		}
	}

	private void formWindowClosed(java.awt.event.WindowEvent evt)
	{// GEN-FIRST:event_formWindowClosed
		setVisible(false);
	}// GEN-LAST:event_formWindowClosed

	private void helpButtonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_helpButtonActionPerformed

		go2Webpage(Constants.OFFICIAL_SITE);
	}// GEN-LAST:event_helpButtonActionPerformed

	private void checkUpdates(boolean isUserClick)
	{
		if(null == server || UpdateCheckFactory.getUpdateChecker() == null)
		{
			if(isUserClick)
			{
				JOptionPane.showMessageDialog(null, "You must start hyk-proxy-client first!");
			}
			
		}
		else
		{
			try
			{
				ReleaseDetail detail = UpdateCheckFactory.getUpdateChecker().checkForUpdates().getNewerRelease();
				if(null != detail)
				{
					getUpdatesInfoDialog().start(detail);
				}
				else
				{
					if(isUserClick)
					{
						JOptionPane.showMessageDialog(null, "Your hyk-proxy is the latest!");
					}
				}
			}
			catch(Exception e)
			{
				if(isUserClick)
				{
					JOptionPane.showMessageDialog(null, "Failed to check for updates! Please see log for details!");
				}	
				logger.error("Failed to check for updates!", e);
			}
		}
	}
	
	private void upgradeButtonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_upgradeButtonActionPerformed
		checkUpdates(true);

	}// GEN-LAST:event_upgradeButtonActionPerformed

	private void exitButtonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_exitButtonActionPerformed
		exit();
	}// GEN-LAST:event_exitButtonActionPerformed

	private void configButtonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_configButtonActionPerformed
		try
		{
			getConfigDialog().start();
		}
		catch(IOException ex)
		{
			logger.error(null, ex);
		}
	}// GEN-LAST:event_configButtonActionPerformed

	private void executeButtonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_executeButtonActionPerformed
		updateExeucteButton();
	}// GEN-LAST:event_executeButtonActionPerformed

	public static void go2Webpage(String site)
	{
		try
		{
			Desktop desktop = Desktop.getDesktop();
			desktop.browse(new URI(site));
		}
		catch(Exception e)
		{
			logger.error("Failed to go to web site!", e);
		}

	}

	private void appHomepageLabelMouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_appHomepageLabelMouseClicked
		go2Webpage(Constants.OFFICIAL_SITE);
	}// GEN-LAST:event_appHomepageLabelMouseClicked

	private void jLabel1MouseClicked(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jLabel1MouseClicked
		go2Webpage("http://twitter.com/yinqiwen");
	}// GEN-LAST:event_jLabel1MouseClicked

	private void shareAppIdButtonActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_shareAppIdButtonActionPerformed

		new Thread(new Runnable()
		{
			@Override
			public void run()
			{
				try
				{
					String result = ClientUtils.getMasterNodeService(ConfigService.getDefaultConfig()).shareMyAppId(
							shareAppIdTextField.getText().trim(), null);
					JOptionPane.showMessageDialog(null, result);
				}
				catch(Exception ex)
				{
					logger.error("", ex);
					JOptionPane.showMessageDialog(null, "Failed to share the appid!" + ex.getMessage());
				}

			}
		}).start();

	}// GEN-LAST:event_shareAppIdButtonActionPerformed

	private void appHomepageLabelMouseMoved(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_appHomepageLabelMouseMoved
		// TODO add your handling code here:
		evt.getComponent().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

	}// GEN-LAST:event_appHomepageLabelMouseMoved

	private void jLabel1MouseMoved(java.awt.event.MouseEvent evt)
	{// GEN-FIRST:event_jLabel1MouseMoved
		evt.getComponent().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
	}// GEN-LAST:event_jLabel1MouseMoved

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
	{// GEN-FIRST:event_jButton1ActionPerformed
		new Thread(new Runnable()
		{
			@Override
			public void run()
			{
				try
				{
					String result = ClientUtils.getMasterNodeService(ConfigService.getDefaultConfig()).unshareMyAppid(
							shareAppIdTextField.getText().trim(), null);
					JOptionPane.showMessageDialog(null, result);
				}
				catch(Exception ex)
				{
					logger.error("", ex);
					JOptionPane.showMessageDialog(null, "Failed to unshare the appid!" + ex.getMessage());
				}

			}

		}).start();

	}// GEN-LAST:event_jButton1ActionPerformed

	protected LocalProxyServer getHttpServer() throws RpcException, Exception
	{
		if(null == server)
		{
			server = new LocalProxyServer();
		}
		return server;
	}

	protected void updateExeucteButton()
	{
		try
		{
			hasStart = !hasStart;
			if(hasStart)
			{
				final LocalProxyServer temp = getHttpServer();
				statusTextArea.setText("Starting...");
				statusLable.setText("Starting...");
				new Thread(new Runnable()
				{
					public void run()
					{
						try
						{
							temp.launch(new StatusMonitor()
							{

								@Override
								public void notifyStatus(String status)
								{
									statusLable.setText(status);
									statusTextArea.append(status);
									statusTextArea.append("\n");
								}

								@Override
								public void clearStatusHistory()
								{
									statusTextArea.setText("");
								}

								@Override
								public void notifyRunDetail(String detail)
								{
									statusTextArea.append(detail);
									statusTextArea.append("\n");
								}
							});
							checkUpdates(false);
						}
						catch(Exception ex)
						{
							JOptionPane.showMessageDialog(null, ex.getMessage());
						}
					}
				}).start();

				executeButton.setIcon(ImageUtil.STOP); // NOI18N
				executeButton.setText("Stop");
			}
			else
			{
				getHttpServer().stop();
				statusTextArea.setText("Stoped");
				statusLable.setText("Stoped");
				executeButton.setIcon(ImageUtil.START); // NOI18N
				executeButton.setText("Start");
			}
		}
		catch(Exception e)
		{
			JOptionPane.showMessageDialog(null, e.getMessage());
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{

			public void run()
			{
				try
				{
					new GUILauncher().setVisible(true);
				}
				catch(Exception ex)
				{
					logger.error("", ex);
				}
			}
		});
	}

	protected ConfigDialog getConfigDialog()
	{
		if(null == config)
		{
			final ConfigDialog dialog = new ConfigDialog(new javax.swing.JFrame(), true);
			config = dialog;
			java.awt.EventQueue.invokeLater(new Runnable()
			{

				public void run()
				{
					dialog.addWindowListener(new java.awt.event.WindowAdapter()
					{

						public void windowClosing(java.awt.event.WindowEvent e)
						{
							dialog.setVisible(false);
						}
					});
					dialog.setVisible(true);
				}
			});
		}
		return config;
	}

	protected UpdatesInfoDialog getUpdatesInfoDialog()
	{
		if(null == updateInfo)
		{
			final UpdatesInfoDialog dialog = new UpdatesInfoDialog(new javax.swing.JFrame(), true);
			updateInfo = dialog;
			java.awt.EventQueue.invokeLater(new Runnable()
			{

				public void run()
				{
					dialog.addWindowListener(new java.awt.event.WindowAdapter()
					{

						public void windowClosing(java.awt.event.WindowEvent e)
						{
							dialog.setVisible(false);
							updateInfo = null;
						}
					});
					dialog.setVisible(true);
				}
			});
		}
		return updateInfo;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel		appHomepageLabel;
	private javax.swing.JButton		configButton;
	private javax.swing.JButton		executeButton;
	private javax.swing.JButton		exitButton;
	private javax.swing.JButton		helpButton;
	private javax.swing.JButton		jButton1;
	private javax.swing.JLabel		jLabel1;
	private javax.swing.JLabel		jLabel2;
	private javax.swing.JLabel		jLabel3;
	private javax.swing.JLabel		jLabel4;
	private javax.swing.JLabel		jLabel5;
	private javax.swing.JLabel		jLabel6;
	private javax.swing.JPanel		jPanel1;
	private javax.swing.JPanel		jPanel2;
	private javax.swing.JPanel		jPanel3;
	private javax.swing.JScrollPane	jScrollPane1;
	private javax.swing.JScrollPane	jScrollPane2;
	private javax.swing.JTabbedPane	jTabbedPane1;
	private javax.swing.JTextArea	jTextArea2;
	private javax.swing.JButton		shareAppIdButton;
	private javax.swing.JTextField	shareAppIdTextField;
	private javax.swing.JLabel		statusLable;
	private javax.swing.JTextArea	statusTextArea;
	private javax.swing.JButton		upgradeButton;
	// End of variables declaration//GEN-END:variables
	private ConfigDialog			config		= null;
	private UpdatesInfoDialog		updateInfo	= null;
	private boolean					hasStart	= false;
	private LocalProxyServer		server;
	private SysTray					tray;
}
